Example/CalendarExample/Controllers/BindingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CalendarExample.Controllers
{
    public class BindingController : Controller
    {
        //
        // GET: /Calendar/

        public ActionResult Index()
        {
            return View();
        }

        Person[] PersonList =  {
                                  new Person() {
                                      ID = 1,
                                      Name = new Name() { First = "Adrian", Last = "Holland"},
                                      Address = new Address() {
                                          Street = "Jackson Crt",
                                          City = "Strathfieldsaye",
                                          State = "Victoria",
                                          Country = "Australia",
                                          Postcode = "3553"
                                      }
                                  },

                                  new Person(){
                                      ID = 2,
                                      Name = new Name() { First = "Sam", Last = "Taylor"},
                                      Address = new Address() {
                                          Street = "Pines Rd",
                                          City = "Robe",
                                          State = "South Australia",
                                          Country = "Australia",
                                          Postcode = "8343"
                                      }
                                  }, 

                                  new Person() {
                                      ID = 3,
                                      Name = new Name() { First = "Greg", Last = "Jones"},
                                      Address = new Address() {
                                          Street = "Yates Blvd",
                                          City = "Caroline Springs",
                                          State = "Victoria",
                                          Country = "Australia",
                                          Postcode = "3345"
                                      }
                                  }
                               };

        /// <summary>
        /// Return a list of people and their ID's
        /// </summary>
        /// <returns></returns>
        public ActionResult List()
        {
            return Json(new { Success = true, Items = PersonList.Select(p => new { p.ID, Name = p.Name }) });
        }

        /// <summary>
        /// Return a single model object
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Object(int id)
        {
            return Json(new { Success = true, Person = PersonList.Where(p => p.ID == id).FirstOrDefault() });
        }

        public class Person
        {
            public int ID { get; set; }
            public Name Name { get; set; }
            public Address Address { get; set; }
        }
        public class Name
        {
            public string First { get; set; }
            public string Last { get; set; }
        }

        public class Address
        {
            public string Street { get; set; }
            public string City { get; set; }
            public string State { get; set; }
            public string Postcode { get; set; }
            public string Country { get; set; }
        }
    }
}

Example/CalendarExample/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CalendarExample.Controllers
{
    public class CalendarController : Controller
    {
        //
        // GET: /Calendar/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Example/CalendarExample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CalendarExample.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Example/CalendarExample/Controllers/ResourceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CalendarExample.Controllers
{
    public class ResourceController : Controller
    {
        public ActionResult JSTmpl(string viewController, string viewAction, string dialect = "string")
        {
            return this.JSTemplate(viewController, viewAction, dialect:dialect);
        }

    }
}

Example/CalendarExample/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CalendarExample.Controllers
{
    public class TeamController : Controller
    {
        //
        // GET: /Team/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Example/CalendarExample/Views/Binding/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@section head {
    @Html.IncludeJSTemplates(dialect:"dom")

    <style type="text/css">
        .field
        {
            margin-top: 5px;
        }

        .field .label
        {
            width: 200px;
            display: inline-block;
            float:left;
        }

        .field .value
        {
            display: block;
            margin-left: 205px;
        }
    </style>
}
<h2>Binding Example</h2>

<div id="personSelector"></div>
<fieldset>
    <legend>Person</legend>
    <div id="person"></div>
</fieldset>

<button id="adrian">Adrian</button>

Example/CalendarExample/Views/Calendar/Index.cshtml
@{
    Layout = "~/Views/Shared/Layout.cshtml";
}

@section head{
    @Html.IncludeJSTemplates()
    <link type="text/css" rel="stylesheet" href="~/Content/calendar.css" />
}

<div id="calendar"></div>


Example/CalendarExample/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>JSRazor Examples</h2>
<ul>
    <li>@Html.ActionLink("Calendar", "Index", "Calendar")</li>
    <li>@Html.ActionLink("Data Binding", "Index", "Binding")</li>
    <li>@Html.ActionLink("Team (More Bindings)", "Index", "Team")</li>
</ul>

Example/CalendarExample/Views/Shared/Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Layout</title>
     <script src="@Url.Content("~/Scripts/jquery.min.js")"></script>
     <script src="@Url.Content("~/Scripts/CubeBuild.Bindings.js")"></script>
    @RenderSection("head", false)
</head>
<body>
    @RenderBody()
</body>
</html>

Example/CalendarExample/Views/Team/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@section head {
    @Html.IncludeJSTemplates(dialect: "dom")
}
<h2>Team Page</h2>
<p>This page uses bindings, template and helper bindings to keep the page in sync with the underlying data model.</p>
<div id="team"></div>
<button onclick="changeall()">Update</button>